name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update package lists and install core build tools
        run: |
          sudo apt-get update
          # Install essential build tools, Meson, and Ninja.
          sudo apt-get install -y build-essential meson ninja-build

      - name: Install CUDA Toolkit (for nvcc)
        run: |
          # Download the repository pin file (for Ubuntu 22.04) and move it to the apt preferences.
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          # Import NVIDIA key (apt-key is deprecated, but is still used here for simplicity).
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          # Add the CUDA repository.
          echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /" | \
            sudo tee /etc/apt/sources.list.d/cuda.list
          sudo apt-get update
          # Install CUDA. (This installs nvcc along with other tools.)
          sudo apt-get install -y cuda

      - name: Add CUDA bin to PATH
        run: echo "/usr/local/cuda/bin" >> $GITHUB_PATH

      - name: Configure project with Meson
        run: meson setup builddir

      - name: Build project with Meson
        run: meson compile -C builddir
